import { type NextPage } from "next";
import Head from "next/head";
import { api } from "$/utils/api";
import { useState } from "react";
import Link from "next/link";

const Home: NextPage = () => {
  const [input, setInput] = useState("");
  const getAllQuery = api.questions.getAll.useQuery();
  const utils = api.useContext();
  const createMutation = api.questions.create.useMutation({
    onSuccess: (res) => {
      if (res == null) return;

      const data = utils.questions.getAll.getData() ?? [];
      utils.questions.getAll.setData(undefined, [...data, res]);
    },
  });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen flex-col items-center gap-8 bg-neutral-800 p-12">
        <form
          onSubmit={(e) => {
            e.preventDefault();
            void createMutation.mutate({ question: input });
            setInput("");
          }}
          className="flex flex-col gap-2"
        >
          <label className="flex flex-col gap-2 text-neutral-100">
            Add a question
            <input
              type="text"
              className="rounded-md bg-neutral-700 p-2 text-neutral-100 placeholder-neutral-500"
              placeholder="Ask a question..."
              value={input}
              onChange={(e) => setInput(e.target.value)}
            />
          </label>

          <button
            type="submit"
            className="rounded-md bg-blue-600 p-2 font-bold text-neutral-100"
          >
            Add
          </button>
        </form>

        <div className="flex flex-col gap-2">
          {getAllQuery.data?.map((question) => (
            <div
              key={question.id}
              className="flex items-center gap-2 rounded bg-neutral-700 px-6 py-2 text-neutral-100"
            >
              {question.question}

              <Link
                href={`/questions/${question.id}`}
                className="font-medium text-orange-500"
              >
                View
              </Link>
            </div>
          ))}
        </div>
      </main>
    </>
  );
};

export default Home;
